name: Lint Python

on:
  pull_request:

jobs:
  lint:
    name: Lint Python
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.9.x"
      - name: Set up Poetry and upgrade pip
        run: |
          pip install -U pip poetry
      - name: Install flows
        run: |
          pip install -e .
          pip install pylint
      - name: Lint flows
        uses: gabriel-milan/action-pylint@v1
        with:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          path: "shape_challenge/"
          fail: true
          pr-message: true
